version: "3"
services:
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      # Adjust you memory configuration here. At most 50% of the container memory
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    ports:
      - 8082:9200
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kib01
    environment:
      XPACK_APM_SERVICEMAPENABLED: "true"
      # Change the ecryption key
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      LOGGING_ROOT_LEVEL: error
    ports:
      - 8081:5601
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
networks:
  elastic:
