services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - wordpress-files:/var/www/html
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
volumes:
  db_data:
  wordpress-files:
