services:
  app:
    # Replace yourNamespace with your namespace as shown in Docker Deploy
    # Replace yourapp with the name of your image
    image: registry.dockerdeploy.cloud/yourNamespace/yourapp
    ports:
      # If your image is exposing a different port, change it in the right side. E.g.: "80:3000"
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
