services:
  db:
    image: mariadb
    environment:
      # Change all this to make it secure
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: db
      MYSQL_USER: YourUser
      MYSQL_PASSWORD: YourPassword
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    expose:
      # Only accesible inside the deployment (host name is db)
      - 3306
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  data:
