services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      # Change credentials
      - POSTGRES_USER=YourUser
      - POSTGRES_PASSWORD=YourPassword
      - POSTGRES_DB=postgres #optional
    expose:
      # Only accesible in the deployment (hostname is postgres)
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      # Change credentials
      - PGADMIN_DEFAULT_EMAIL=youremail@domain.com
      - PGADMIN_DEFAULT_PASSWORD=YourPGAdminPassword
    ports:
      - "80:80"

volumes:
  pgdata:
    driver: local
