## You can use this as template to build and deploy your apps to Docker Deploy when you push to main.
## Make sure that you replace the following values
##   - YOUR_REGISTRY_USERNAME: you see it when your press **Show registry credentials** in your deployment page
##   - YOUR_REGISTRY_NAMESPACE: you see it when your press **Show registry credentials** in your deployment page
##   - YOUR_APP_NAME: A name for your docker image
##   - YOUR_APP_ID: Is in the URL of your app page `dockerdeploy.cloud/dashboard/deployments/HERE`

name: Build and deploy
on:
  # Will run on when you push to main
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.dockerdeploy.cloud
          # Replace with your registry username
          username: YOUR_REGISTRY_USERNAME
          password: ${{ secrets.DD_REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # Replace with your namespace and app name
          tags: registry.dockerdeploy.cloud/YOUR_REGISTRY_NAMESPACE/YOUR_APP_NAME

      - name: Re-deploy
        run: |
          curl -XPUT -f -H 'Authorization: PAT ${{ secrets.DD_TOKEN }}' \
          'https://api.dockerdeploy.cloud/api/deployments/YOUR_APP_ID/deploy'
